# Generated by Django 4.2 on 2023-05-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNum', models.CharField(max_length=200)),
                ('fromAndTo', models.CharField(max_length=200)),
                ('departure', models.DateTimeField(max_length=200)),
                ('arrival', models.DateTimeField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
