# Generated by Django 4.2 on 2023-05-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_flights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
