# Generated by Django 4.2 on 2023-05-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_flightnum_flight_flighttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flightId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.flight')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
