# Generated by Django 4.2 on 2023-05-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_user_last_login_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWayFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightType', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departureDate', models.DateTimeField(max_length=200)),
                ('totalAmount', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Flight',
            new_name='RoundTripFlight',
        ),
        migrations.DeleteModel(
            name='BookedFlight',
        ),
    ]
