# Generated by Django 4.2 on 2023-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_onewayflight_rename_flight_roundtripflight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedOneWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightType', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departureDate', models.DateTimeField(max_length=200)),
                ('totalAmount', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookedRoundTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightType', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departureDate', models.DateTimeField(max_length=200)),
                ('returnDate', models.DateTimeField(max_length=200)),
                ('totalAmount', models.CharField(max_length=200)),
            ],
        ),
    ]
