# Generated by Django 4.2 on 2023-05-14 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_bookedoneway_bookedroundtrip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='bookedoneway',
            name='user',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookedroundtrip',
            name='user',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookedoneway',
            name='departureDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookedoneway',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedoneway',
            name='flightType',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookedoneway',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='departureDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='flightType',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='returnDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
