# Generated by Django 4.2 on 2023-05-14 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_add_user_to_bookedoneway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedoneway',
            name='departureDate',
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedoneway',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedoneway',
            name='flightType',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedoneway',
            name='totalAmount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedoneway',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='departureDate',
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='flightType',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='returnDate',
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='totalAmount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
