# Generated by Django 4.2 on 2023-05-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_bookedoneway_departuredate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedoneway',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookedroundtrip',
            name='user',
        ),
    ]
